import React, { useEffect } from "react";
import Head from "next/head";
import { motion } from "framer-motion";
import { useTranslation } from "next-i18next";
import { GetStaticProps, InferGetStaticPropsType } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { analytics } from "../lib";

const Home = (props: InferGetStaticPropsType<typeof getStaticProps>) => {
  const { t } = useTranslation("common");

  useEffect(() => {
    console.log(props);
    analytics.track("HomePage visited");
  }, []);

  return (
    <div style={{ padding: "2rem" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{t("title")}</h1>
        <motion.div
          style={{ width: 100, height: 100, backgroundColor: "white" }}
          animate={{ x: 200 }}
        ></motion.div>
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale ?? "no", ["common"])),
  },
});
export default Home;
