import React from "react";
import Head from "next/head";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <div style={{ padding: "2rem" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hei</h1>
        <motion.div
          style={{ width: 100, height: 100, backgroundColor: "white" }}
          animate={{ x: 200 }}
        ></motion.div>
      </main>
    </div>
  );
}
